apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 005165627580.dkr.ecr.eu-west-1.amazonaws.com/eve-project/backend:latest
          ports:
            - containerPort: 8000
