# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: backend
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/justingodden/eve-project.git
#     targetRevision: HEAD
#     path: argocd/manifests/backend
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: backend
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       selfHeal: true
#       prune: true
