apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: "*"
    helm:
      releaseName: nginx
      valuesObject:
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: eve-project.com
          path: /nginx(/|$)(.*)
          pathType: Prefix
          annotations:
            # nginx.ingress.kubernetes.io/use-regex: "true"
            nginx.ingress.kubernetes.io/rewrite-target: /$2
            nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
