apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: "*"
    helm:
      releaseName: nginx
      parameters:
        - name: "service.type"
          value: "ClusterIP"
        - name: "ingress.enabled"
          value: "true"
        - name: "ingress.hostname"
          value: "eve-project.com"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
