apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: collect-summarize-template
spec:
  entrypoint: workflow
  templates:
    - name: workflow
      dag:
        tasks:
          - name: collect
            template: data-collector
          - name: summarize
            template: summarizer
            dependencies: [collect]
    - name: data-collector
      container:
        image: 005165627580.dkr.ecr.eu-west-1.amazonaws.com/eve-project/data-collector:latest
    - name: summarizer
      container:
        image: 005165627580.dkr.ecr.eu-west-1.amazonaws.com/eve-project/summarizer:latest
